// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DVineAD_LL
double DVineAD_LL(NumericVector u, NumericVector v, double theta);
RcppExport SEXP DVineAD_DVineAD_LL(SEXP uSEXP, SEXP vSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(DVineAD_LL(u, v, theta));
    return rcpp_result_gen;
END_RCPP
}
// DVineVec2RVineVec
NumericVector DVineVec2RVineVec(int d, NumericVector dvinegrad, int TruncLevel);
RcppExport SEXP DVineAD_DVineVec2RVineVec(SEXP dSEXP, SEXP dvinegradSEXP, SEXP TruncLevelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dvinegrad(dvinegradSEXP);
    Rcpp::traits::input_parameter< int >::type TruncLevel(TruncLevelSEXP);
    rcpp_result_gen = Rcpp::wrap(DVineVec2RVineVec(d, dvinegrad, TruncLevel));
    return rcpp_result_gen;
END_RCPP
}
// DVineAD_EstablishTape
void DVineAD_EstablishTape(NumericMatrix X, NumericVector theta, int TruncLevel);
RcppExport SEXP DVineAD_DVineAD_EstablishTape(SEXP XSEXP, SEXP thetaSEXP, SEXP TruncLevelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type TruncLevel(TruncLevelSEXP);
    DVineAD_EstablishTape(X, theta, TruncLevel);
    return R_NilValue;
END_RCPP
}
// DVineAD_LogLik
double DVineAD_LogLik(NumericVector theta);
RcppExport SEXP DVineAD_DVineAD_LogLik(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(DVineAD_LogLik(theta));
    return rcpp_result_gen;
END_RCPP
}
// DVineAD_LogLikGrad
NumericVector DVineAD_LogLikGrad(NumericVector theta);
RcppExport SEXP DVineAD_DVineAD_LogLikGrad(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(DVineAD_LogLikGrad(theta));
    return rcpp_result_gen;
END_RCPP
}
// DVineAD_LogLikHess
NumericMatrix DVineAD_LogLikHess(NumericVector theta);
RcppExport SEXP DVineAD_DVineAD_LogLikHess(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(DVineAD_LogLikHess(theta));
    return rcpp_result_gen;
END_RCPP
}
