# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DVineAD_LL <- function(u, v, theta) {
    .Call('DVineAD_DVineAD_LL', PACKAGE = 'DVineAD', u, v, theta)
}

DVineVec2RVineVec <- function(d, dvinegrad, TruncLevel) {
    .Call('DVineAD_DVineVec2RVineVec', PACKAGE = 'DVineAD', d, dvinegrad, TruncLevel)
}

DVineAD_EstablishTape <- function(X, theta, TruncLevel) {
    invisible(.Call('DVineAD_DVineAD_EstablishTape', PACKAGE = 'DVineAD', X, theta, TruncLevel))
}

DVineAD_LogLik <- function(theta) {
    .Call('DVineAD_DVineAD_LogLik', PACKAGE = 'DVineAD', theta)
}

DVineAD_LogLikGrad <- function(theta) {
    .Call('DVineAD_DVineAD_LogLikGrad', PACKAGE = 'DVineAD', theta)
}

DVineAD_LogLikHess <- function(theta) {
    .Call('DVineAD_DVineAD_LogLikHess', PACKAGE = 'DVineAD', theta)
}

